---
- name: Check timezone
  command: "timedatectl show"
  register: timedatectl_current
  changed_when: false

- name: Set timezone
  command: timedatectl set-timezone {{ timezone }}
  changed_when: timezone not in timedatectl_current.stdout
